[talos]
version = "v1.10.0"
[talos.talosctl]
package = "siderolabs/talos"
srcHash = "sha256-T/iFzMl3+tZu3EFNyof+QIywJA7ZTLm1asvy/q97Dus="
vendorHash = "sha256-aFxeKyBcMdw5WOTRvXRofO2jA7rrQNaJGrZw3mcqvXE="
[talos.images.installer]
ref = "ghcr.io/siderolabs/installer"
digest = "sha256:43f1f152ef523d1d777248af7d410b6184871d4d31f39d7b0ffecd198b984af6"
[talos.images.imager]
ref = "ghcr.io/siderolabs/imager"
digest = "sha256:4b3c4df4ad0763965349bfb48c4242b880bf8d82ae2bd1f053694ad7f4bf37e1"
[talos.images.extensions]
ref = "ghcr.io/siderolabs/extensions"
digest = "sha256:8ef9c1df17d1179282a2e8b7fb10494a29fa5b1247463d8efe634b4329ef49eb"
[talos.images.overlays]
ref = "ghcr.io/siderolabs/overlays"
digest = "sha256:033f9d44aa70970f926564d68b6050c81c24158b4b8c375b19dcbadcfa774b62"
